changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Epics
      labels:
        - Epic
    - title: Features
      labels:
        - Feature
    - title: User Stories
      labels:
        - User Story
    - title: Everything else
      labels:
        - "*"
